site_name: ENSSAT Projects
theme:
  name: null
  custom_dir: theme

  logo: favicon.ico
  favicon: favicon.ico

  palette:
    primary: black
    accent: orange

  features:
    - navigation.tabs


markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - frontmatter:

nav:
  - Java:
    - Space Invader: projects/space-invader.md
    - Candy Crush: projects/candy-crush.md
  - Python:
    - Images recognition: projects/images-recognition.md
    - Data mining: projects/data-mining.md
    - Simulateur de trafic: projects/calcroad-trafic-simulator.md
    - App, Gestion de playlists: projects/sortify-playlists-management.md
  - C++:
    - 3D engine: projects/3d-engine.md
    - OpenGL game: projects/opengl-game.md
  - Arduino:
    - Bluetooth trafic light: projects/bluetooth-trafic-light.md
